env:
  browser: true
  es2021: true
extends:
 'airbnb-base'
globals:
  Atomics: readonly
  SharedArrayBuffer: readonly
parserOptions:
  ecmaVersion: latest
  sourceType: module
rules: 
  no-console: off
import/extensions: off
